name: JSDoc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: buildJsDoc
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./source
        recurse: true
        output_dir: ./out